// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/barry-hennessy/bones/repo"
	"sync"
)

// Ensure, that TxMock does implement Tx.
// If this is not the case, regenerate this file with moq.
var _ Tx = &TxMock{}

// TxMock is a mock implementation of Tx.
//
//	func TestSomethingThatUsesTx(t *testing.T) {
//
//		// make and configure a mocked Tx
//		mockedTx := &TxMock{
//			CloseFunc: func(contextMoqParam context.Context) error {
//				panic("mock out the Close method")
//			},
//			CommitFunc: func(contextMoqParam context.Context) error {
//				panic("mock out the Commit method")
//			},
//			RollbackFunc: func(contextMoqParam context.Context) error {
//				panic("mock out the Rollback method")
//			},
//		}
//
//		// use mockedTx in code that requires Tx
//		// and then make assertions.
//
//	}
type TxMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func(contextMoqParam context.Context) error

	// CommitFunc mocks the Commit method.
	CommitFunc func(contextMoqParam context.Context) error

	// RollbackFunc mocks the Rollback method.
	RollbackFunc func(contextMoqParam context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// Commit holds details about calls to the Commit method.
		Commit []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// Rollback holds details about calls to the Rollback method.
		Rollback []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
	}
	lockClose    sync.RWMutex
	lockCommit   sync.RWMutex
	lockRollback sync.RWMutex
}

// Close calls CloseFunc.
func (mock *TxMock) Close(contextMoqParam context.Context) error {
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	if mock.CloseFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CloseFunc(contextMoqParam)
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedTx.CloseCalls())
func (mock *TxMock) CloseCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// ResetCloseCalls reset all the calls that were made to Close.
func (mock *TxMock) ResetCloseCalls() {
	mock.lockClose.Lock()
	mock.calls.Close = nil
	mock.lockClose.Unlock()
}

// Commit calls CommitFunc.
func (mock *TxMock) Commit(contextMoqParam context.Context) error {
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockCommit.Lock()
	mock.calls.Commit = append(mock.calls.Commit, callInfo)
	mock.lockCommit.Unlock()
	if mock.CommitFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CommitFunc(contextMoqParam)
}

// CommitCalls gets all the calls that were made to Commit.
// Check the length with:
//
//	len(mockedTx.CommitCalls())
func (mock *TxMock) CommitCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockCommit.RLock()
	calls = mock.calls.Commit
	mock.lockCommit.RUnlock()
	return calls
}

// ResetCommitCalls reset all the calls that were made to Commit.
func (mock *TxMock) ResetCommitCalls() {
	mock.lockCommit.Lock()
	mock.calls.Commit = nil
	mock.lockCommit.Unlock()
}

// Rollback calls RollbackFunc.
func (mock *TxMock) Rollback(contextMoqParam context.Context) error {
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockRollback.Lock()
	mock.calls.Rollback = append(mock.calls.Rollback, callInfo)
	mock.lockRollback.Unlock()
	if mock.RollbackFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.RollbackFunc(contextMoqParam)
}

// RollbackCalls gets all the calls that were made to Rollback.
// Check the length with:
//
//	len(mockedTx.RollbackCalls())
func (mock *TxMock) RollbackCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockRollback.RLock()
	calls = mock.calls.Rollback
	mock.lockRollback.RUnlock()
	return calls
}

// ResetRollbackCalls reset all the calls that were made to Rollback.
func (mock *TxMock) ResetRollbackCalls() {
	mock.lockRollback.Lock()
	mock.calls.Rollback = nil
	mock.lockRollback.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *TxMock) ResetCalls() {
	mock.lockClose.Lock()
	mock.calls.Close = nil
	mock.lockClose.Unlock()

	mock.lockCommit.Lock()
	mock.calls.Commit = nil
	mock.lockCommit.Unlock()

	mock.lockRollback.Lock()
	mock.calls.Rollback = nil
	mock.lockRollback.Unlock()
}

// Ensure, that TestFactoryMock does implement TestFactory.
// If this is not the case, regenerate this file with moq.
var _ TestFactory = &TestFactoryMock{}

// TestFactoryMock is a mock implementation of TestFactory.
//
//	func TestSomethingThatUsesTestFactory(t *testing.T) {
//
//		// make and configure a mocked TestFactory
//		mockedTestFactory := &TestFactoryMock{
//			BeginFunc: func(contextMoqParam context.Context) (repo.Tx, TestRepos, error) {
//				panic("mock out the Begin method")
//			},
//		}
//
//		// use mockedTestFactory in code that requires TestFactory
//		// and then make assertions.
//
//	}
type TestFactoryMock struct {
	// BeginFunc mocks the Begin method.
	BeginFunc func(contextMoqParam context.Context) (repo.Tx, TestRepos, error)

	// calls tracks calls to the methods.
	calls struct {
		// Begin holds details about calls to the Begin method.
		Begin []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
	}
	lockBegin sync.RWMutex
}

// Begin calls BeginFunc.
func (mock *TestFactoryMock) Begin(contextMoqParam context.Context) (repo.Tx, TestRepos, error) {
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockBegin.Lock()
	mock.calls.Begin = append(mock.calls.Begin, callInfo)
	mock.lockBegin.Unlock()
	if mock.BeginFunc == nil {
		var (
			txOut        repo.Tx
			testReposOut TestRepos
			errOut       error
		)
		return txOut, testReposOut, errOut
	}
	return mock.BeginFunc(contextMoqParam)
}

// BeginCalls gets all the calls that were made to Begin.
// Check the length with:
//
//	len(mockedTestFactory.BeginCalls())
func (mock *TestFactoryMock) BeginCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockBegin.RLock()
	calls = mock.calls.Begin
	mock.lockBegin.RUnlock()
	return calls
}

// ResetBeginCalls reset all the calls that were made to Begin.
func (mock *TestFactoryMock) ResetBeginCalls() {
	mock.lockBegin.Lock()
	mock.calls.Begin = nil
	mock.lockBegin.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *TestFactoryMock) ResetCalls() {
	mock.lockBegin.Lock()
	mock.calls.Begin = nil
	mock.lockBegin.Unlock()
}

// Ensure, that TestDirectFactoryMock does implement TestDirectFactory.
// If this is not the case, regenerate this file with moq.
var _ TestDirectFactory = &TestDirectFactoryMock{}

// TestDirectFactoryMock is a mock implementation of TestDirectFactory.
//
//	func TestSomethingThatUsesTestDirectFactory(t *testing.T) {
//
//		// make and configure a mocked TestDirectFactory
//		mockedTestDirectFactory := &TestDirectFactoryMock{
//			OpenFunc: func(contextMoqParam context.Context) (TestRepos, func(context.Context) error, error) {
//				panic("mock out the Open method")
//			},
//		}
//
//		// use mockedTestDirectFactory in code that requires TestDirectFactory
//		// and then make assertions.
//
//	}
type TestDirectFactoryMock struct {
	// OpenFunc mocks the Open method.
	OpenFunc func(contextMoqParam context.Context) (TestRepos, func(context.Context) error, error)

	// calls tracks calls to the methods.
	calls struct {
		// Open holds details about calls to the Open method.
		Open []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
	}
	lockOpen sync.RWMutex
}

// Open calls OpenFunc.
func (mock *TestDirectFactoryMock) Open(contextMoqParam context.Context) (TestRepos, func(context.Context) error, error) {
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockOpen.Lock()
	mock.calls.Open = append(mock.calls.Open, callInfo)
	mock.lockOpen.Unlock()
	if mock.OpenFunc == nil {
		var (
			testReposOut TestRepos
			fnOut        func(context.Context) error
			errOut       error
		)
		return testReposOut, fnOut, errOut
	}
	return mock.OpenFunc(contextMoqParam)
}

// OpenCalls gets all the calls that were made to Open.
// Check the length with:
//
//	len(mockedTestDirectFactory.OpenCalls())
func (mock *TestDirectFactoryMock) OpenCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockOpen.RLock()
	calls = mock.calls.Open
	mock.lockOpen.RUnlock()
	return calls
}

// ResetOpenCalls reset all the calls that were made to Open.
func (mock *TestDirectFactoryMock) ResetOpenCalls() {
	mock.lockOpen.Lock()
	mock.calls.Open = nil
	mock.lockOpen.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *TestDirectFactoryMock) ResetCalls() {
	mock.lockOpen.Lock()
	mock.calls.Open = nil
	mock.lockOpen.Unlock()
}
