// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/barry-hennessy/bones/observability"
	"sync"
)

// Ensure, that TracerMock does implement observability.Tracer.
// If this is not the case, regenerate this file with moq.
var _ observability.Tracer = &TracerMock{}

// TracerMock is a mock implementation of observability.Tracer.
//
//	func TestSomethingThatUsesTracer(t *testing.T) {
//
//		// make and configure a mocked observability.Tracer
//		mockedTracer := &TracerMock{
//			StartFunc: func(ctx context.Context, name string, cfg observability.StartConfig) (context.Context, observability.Span) {
//				panic("mock out the Start method")
//			},
//		}
//
//		// use mockedTracer in code that requires observability.Tracer
//		// and then make assertions.
//
//	}
type TracerMock struct {
	// StartFunc mocks the Start method.
	StartFunc func(ctx context.Context, name string, cfg observability.StartConfig) (context.Context, observability.Span)

	// calls tracks calls to the methods.
	calls struct {
		// Start holds details about calls to the Start method.
		Start []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Cfg is the cfg argument value.
			Cfg observability.StartConfig
		}
	}
	lockStart sync.RWMutex
}

// Start calls StartFunc.
func (mock *TracerMock) Start(ctx context.Context, name string, cfg observability.StartConfig) (context.Context, observability.Span) {
	callInfo := struct {
		Ctx  context.Context
		Name string
		Cfg  observability.StartConfig
	}{
		Ctx:  ctx,
		Name: name,
		Cfg:  cfg,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	if mock.StartFunc == nil {
		var (
			contextOut context.Context
			spanOut    observability.Span
		)
		return contextOut, spanOut
	}
	return mock.StartFunc(ctx, name, cfg)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedTracer.StartCalls())
func (mock *TracerMock) StartCalls() []struct {
	Ctx  context.Context
	Name string
	Cfg  observability.StartConfig
} {
	var calls []struct {
		Ctx  context.Context
		Name string
		Cfg  observability.StartConfig
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}

// Ensure, that SpanMock does implement observability.Span.
// If this is not the case, regenerate this file with moq.
var _ observability.Span = &SpanMock{}

// SpanMock is a mock implementation of observability.Span.
//
//	func TestSomethingThatUsesSpan(t *testing.T) {
//
//		// make and configure a mocked observability.Span
//		mockedSpan := &SpanMock{
//			AddLinkFunc: func(link observability.Link)  {
//				panic("mock out the AddLink method")
//			},
//			EndFunc: func()  {
//				panic("mock out the End method")
//			},
//			IsRecordingFunc: func() bool {
//				panic("mock out the IsRecording method")
//			},
//			IsValidFunc: func() bool {
//				panic("mock out the IsValid method")
//			},
//			SetAttributeFunc: func(key string, value string)  {
//				panic("mock out the SetAttribute method")
//			},
//			SpanIDFunc: func() string {
//				panic("mock out the SpanID method")
//			},
//			TraceIDFunc: func() string {
//				panic("mock out the TraceID method")
//			},
//		}
//
//		// use mockedSpan in code that requires observability.Span
//		// and then make assertions.
//
//	}
type SpanMock struct {
	// AddLinkFunc mocks the AddLink method.
	AddLinkFunc func(link observability.Link)

	// EndFunc mocks the End method.
	EndFunc func()

	// IsRecordingFunc mocks the IsRecording method.
	IsRecordingFunc func() bool

	// IsValidFunc mocks the IsValid method.
	IsValidFunc func() bool

	// SetAttributeFunc mocks the SetAttribute method.
	SetAttributeFunc func(key string, value string)

	// SpanIDFunc mocks the SpanID method.
	SpanIDFunc func() string

	// TraceIDFunc mocks the TraceID method.
	TraceIDFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// AddLink holds details about calls to the AddLink method.
		AddLink []struct {
			// Link is the link argument value.
			Link observability.Link
		}
		// End holds details about calls to the End method.
		End []struct {
		}
		// IsRecording holds details about calls to the IsRecording method.
		IsRecording []struct {
		}
		// IsValid holds details about calls to the IsValid method.
		IsValid []struct {
		}
		// SetAttribute holds details about calls to the SetAttribute method.
		SetAttribute []struct {
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value string
		}
		// SpanID holds details about calls to the SpanID method.
		SpanID []struct {
		}
		// TraceID holds details about calls to the TraceID method.
		TraceID []struct {
		}
	}
	lockAddLink      sync.RWMutex
	lockEnd          sync.RWMutex
	lockIsRecording  sync.RWMutex
	lockIsValid      sync.RWMutex
	lockSetAttribute sync.RWMutex
	lockSpanID       sync.RWMutex
	lockTraceID      sync.RWMutex
}

// AddLink calls AddLinkFunc.
func (mock *SpanMock) AddLink(link observability.Link) {
	callInfo := struct {
		Link observability.Link
	}{
		Link: link,
	}
	mock.lockAddLink.Lock()
	mock.calls.AddLink = append(mock.calls.AddLink, callInfo)
	mock.lockAddLink.Unlock()
	if mock.AddLinkFunc == nil {
		return
	}
	mock.AddLinkFunc(link)
}

// AddLinkCalls gets all the calls that were made to AddLink.
// Check the length with:
//
//	len(mockedSpan.AddLinkCalls())
func (mock *SpanMock) AddLinkCalls() []struct {
	Link observability.Link
} {
	var calls []struct {
		Link observability.Link
	}
	mock.lockAddLink.RLock()
	calls = mock.calls.AddLink
	mock.lockAddLink.RUnlock()
	return calls
}

// End calls EndFunc.
func (mock *SpanMock) End() {
	callInfo := struct {
	}{}
	mock.lockEnd.Lock()
	mock.calls.End = append(mock.calls.End, callInfo)
	mock.lockEnd.Unlock()
	if mock.EndFunc == nil {
		return
	}
	mock.EndFunc()
}

// EndCalls gets all the calls that were made to End.
// Check the length with:
//
//	len(mockedSpan.EndCalls())
func (mock *SpanMock) EndCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockEnd.RLock()
	calls = mock.calls.End
	mock.lockEnd.RUnlock()
	return calls
}

// IsRecording calls IsRecordingFunc.
func (mock *SpanMock) IsRecording() bool {
	callInfo := struct {
	}{}
	mock.lockIsRecording.Lock()
	mock.calls.IsRecording = append(mock.calls.IsRecording, callInfo)
	mock.lockIsRecording.Unlock()
	if mock.IsRecordingFunc == nil {
		var (
			bOut bool
		)
		return bOut
	}
	return mock.IsRecordingFunc()
}

// IsRecordingCalls gets all the calls that were made to IsRecording.
// Check the length with:
//
//	len(mockedSpan.IsRecordingCalls())
func (mock *SpanMock) IsRecordingCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIsRecording.RLock()
	calls = mock.calls.IsRecording
	mock.lockIsRecording.RUnlock()
	return calls
}

// IsValid calls IsValidFunc.
func (mock *SpanMock) IsValid() bool {
	callInfo := struct {
	}{}
	mock.lockIsValid.Lock()
	mock.calls.IsValid = append(mock.calls.IsValid, callInfo)
	mock.lockIsValid.Unlock()
	if mock.IsValidFunc == nil {
		var (
			bOut bool
		)
		return bOut
	}
	return mock.IsValidFunc()
}

// IsValidCalls gets all the calls that were made to IsValid.
// Check the length with:
//
//	len(mockedSpan.IsValidCalls())
func (mock *SpanMock) IsValidCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIsValid.RLock()
	calls = mock.calls.IsValid
	mock.lockIsValid.RUnlock()
	return calls
}

// SetAttribute calls SetAttributeFunc.
func (mock *SpanMock) SetAttribute(key string, value string) {
	callInfo := struct {
		Key   string
		Value string
	}{
		Key:   key,
		Value: value,
	}
	mock.lockSetAttribute.Lock()
	mock.calls.SetAttribute = append(mock.calls.SetAttribute, callInfo)
	mock.lockSetAttribute.Unlock()
	if mock.SetAttributeFunc == nil {
		return
	}
	mock.SetAttributeFunc(key, value)
}

// SetAttributeCalls gets all the calls that were made to SetAttribute.
// Check the length with:
//
//	len(mockedSpan.SetAttributeCalls())
func (mock *SpanMock) SetAttributeCalls() []struct {
	Key   string
	Value string
} {
	var calls []struct {
		Key   string
		Value string
	}
	mock.lockSetAttribute.RLock()
	calls = mock.calls.SetAttribute
	mock.lockSetAttribute.RUnlock()
	return calls
}

// SpanID calls SpanIDFunc.
func (mock *SpanMock) SpanID() string {
	callInfo := struct {
	}{}
	mock.lockSpanID.Lock()
	mock.calls.SpanID = append(mock.calls.SpanID, callInfo)
	mock.lockSpanID.Unlock()
	if mock.SpanIDFunc == nil {
		var (
			sOut string
		)
		return sOut
	}
	return mock.SpanIDFunc()
}

// SpanIDCalls gets all the calls that were made to SpanID.
// Check the length with:
//
//	len(mockedSpan.SpanIDCalls())
func (mock *SpanMock) SpanIDCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSpanID.RLock()
	calls = mock.calls.SpanID
	mock.lockSpanID.RUnlock()
	return calls
}

// TraceID calls TraceIDFunc.
func (mock *SpanMock) TraceID() string {
	callInfo := struct {
	}{}
	mock.lockTraceID.Lock()
	mock.calls.TraceID = append(mock.calls.TraceID, callInfo)
	mock.lockTraceID.Unlock()
	if mock.TraceIDFunc == nil {
		var (
			sOut string
		)
		return sOut
	}
	return mock.TraceIDFunc()
}

// TraceIDCalls gets all the calls that were made to TraceID.
// Check the length with:
//
//	len(mockedSpan.TraceIDCalls())
func (mock *SpanMock) TraceIDCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockTraceID.RLock()
	calls = mock.calls.TraceID
	mock.lockTraceID.RUnlock()
	return calls
}
